### ISSUE TITLE
No back to menu

### ISSUE THREAD

**Issue by magdalex** [magdalex/GroceryStoreSystem#11]
Most of the options cannot be backed to menu after being entered, and the program must be entered correctly or closed. (Feedback by Wei Zhu)

**Comment by MagneticReaper** [comment]
i need more opinions on this. should we have a cancel option on every step? that seems like a lot of work XD

**Comment by magdalex** [comment]
What exactly does he mean by "and the program must be entered correctly or closed"?

**Comment by MagneticReaper** [comment]
i guess he's unable to put in bad data?

**Comment by magdalex** [comment]
> i need more opinions on this. should we have a cancel option on every step? that seems like a lot of work XD

Technically, in a functional program and app, yes we should. This is also direct user feedback, meaning we have tangible proof that a customer wanted to go back enough times throughout the process that it bothered them to not have the option. Maybe not on every step, but the main steps should have a back button I think.

**Comment by magdalex** [comment]
> i guess he's unable to put in bad data?

Either Im misunderstanding, or this is a good thing for our system. We just don't allow bad data to be inserted heheh

**Comment by MagneticReaper** [comment]
i looked at the DB. i think it was forcing him to continue with checkout of an empty cart and he didn't want to. you can no longer check out empty carts though. i'll add one or 2 cancel options during checkout.

**Comment by magdalex** [comment]
I've send him a direct message asking him to elaborate. I'll comment here once he replies.

**Comment by magdalex** [comment]
"I think I didn't make it clear. For example, I want to modify my zip code. When I enter this option, if I don't want to modify it, I can only close the program instead of returning to the home page. <Sent image, available on our discord server>. just keep looping"

He's right, there should be more cancel buttons for functions.

**Comment by MagneticReaper** [comment]
not enough time left before deadline to implement
